name: Deploy to GH Pages

on:
  push:
    branches:
      - deploymentPipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run build --if-present

    - name: Deploy
      run: |
        rm -rf node_modules/gh-pages/.cache
        npm run deploy
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
