name: Deploy to GH Pages

on:
  push:
    branches:
      - deploymentPipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run build --if-present

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        DEPLOY_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_DIR: build
